id: c31e677247204bae8ab30d05ad5de4b2
initial_creation_type: ocr
source_metadata:
  volumes:
    5fd835fe5d9e4ea1be6b62dd6b63b575:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: བསླབ་པ་ཀུན་ལས་བཏུས་པ།
      total_pages: 1902
      volume_number: 64
